curl -i -X GET 'node.licious.in/api/user/profile?customer_key=c_jgq53x5k' -H "token:tk_jghephjr"
curl -i -X GET 'node.licious.in/api/user/profile1?customer_key=c_jgq53x5k' -H "token:tk_jghephjr"
curl -i -X GET 'node.licious.in/api/user/profile?customer_key=c_j1gq53x5k' -H "token:tk_jghephjr"
curl -i -X GET 'node.licious.in/api/user/profile?customer_key=c_jgq53x5k' -H "token:tk_jghephjr1"
curl -i -X GET 'node.licious.in/api/user/profile?customer_key=' -H "token:"
